[package]
name = "cumulus-backend"
description = "Native lazy remote storage backend for Jujutsu"
publish = false
version = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
cumulus-proto = { workspace = true }
cumulus-store = { workspace = true }
futures = { workspace = true }
jj-lib = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tonic = { workspace = true, features = ["tls-ring"] }
tracing = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
pollster = { workspace = true }
tempfile = { workspace = true }
